# Generated by Django 5.2.10 on 2026-01-20 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('card_name', models.CharField(max_length=100)),
                ('card_number_mask', models.CharField(max_length=20)),
                ('issuer', models.CharField(max_length=100)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('last_loaded_at', models.DateTimeField(blank=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('pdf_password', models.CharField(blank=True, max_length=255)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_files', to='credit_cards.creditcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardPDFExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=48, unique=True)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('statement_period_begin', models.DateField(blank=True, null=True)),
                ('statement_period_end', models.DateField(blank=True, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('card_number_mask', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('total_amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minimum_amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('extractor_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('extracted', 'Extracted'), ('transformed', 'Transformed'), ('loading', 'Loading'), ('loaded', 'Loaded to DB'), ('error', 'Load Error'), ('superseded', 'Superseded')], default='extracted', max_length=20)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('hidden', models.BooleanField(default=False)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_cards.creditcard')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_extractions', to='credit_cards.creditcardsourcefile')),
            ],
            options={
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='DismissedCreditCardInconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inconsistency_type', models.CharField(choices=[('duplicate', 'Duplicate Transaction'), ('cross_card', 'Cross-Card Match'), ('missing_description', 'Missing Description')], max_length=20)),
                ('transaction_ids', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dismissed_at'],
                'unique_together': {('inconsistency_type', 'transaction_ids')},
            },
        ),
        migrations.CreateModel(
            name='ExtractionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('artifact_type', models.CharField(max_length=50)),
                ('content_type', models.CharField(default='csv', max_length=20)),
                ('data', models.BinaryField()),
                ('data_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('transformer_name', models.CharField(blank=True, default='', max_length=50)),
                ('is_transformable', models.BooleanField(default=False)),
                ('is_transformed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='credit_cards.creditcard')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='credit_cards.creditcardpdfextraction')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_artifacts', to='credit_cards.extractionartifact')),
            ],
            options={
                'ordering': ['artifact_type'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('intl_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('intl_currency', models.CharField(blank=True, default='', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('row_number', models.IntegerField(default=0)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credit_cards.creditcard')),
                ('pdf_extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='credit_cards.creditcardpdfextraction')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='credit_cards.creditcardsourcefile')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='credit_cards.extractionartifact')),
            ],
            options={
                'ordering': ['-date', '-row_number'],
            },
        ),
    ]
