# Generated by Django 5.2.10 on 2026-01-23 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('card_name', models.CharField(max_length=100)),
                ('card_number_mask', models.CharField(max_length=20)),
                ('issuer', models.CharField(max_length=100)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DismissedCreditCardInconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inconsistency_type', models.CharField(choices=[('duplicate', 'Duplicate Transaction'), ('cross_card', 'Cross-Card Match'), ('missing_description', 'Missing Description')], max_length=20)),
                ('transaction_ids', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dismissed_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardPaymentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('match_reasons', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cc_payment_match', to='bank_accounts.banktransaction')),
            ],
            options={
                'db_table': 'credit_cards_creditcardpaymentmatch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('intl_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('intl_currency', models.CharField(blank=True, default='', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('artifact_row_id', models.CharField(blank=True, max_length=50)),
                ('row_number', models.IntegerField(default=0)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credit_cards.creditcard')),
            ],
            options={
                'ordering': ['-date', '-row_number'],
            },
        ),
    ]
