# Generated by Django 5.2.10 on 2026-01-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardtransaction',
            name='reward_points',
        ),
    ]
