# Generated by Django 5.2.10 on 2026-01-23 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_cards', '0001_initial'),
        ('extractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='data_source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_transactions', to='extractions.datasourceartifact'),
        ),
        migrations.AddField(
            model_name='creditcardpaymentmatch',
            name='credit_card_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment_match', to='credit_cards.creditcardtransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='dismissedcreditcardinconsistency',
            unique_together={('inconsistency_type', 'transaction_ids')},
        ),
    ]
