# Generated by Django 5.2.10 on 2026-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='artifact_row_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
