# Generated by Django 5.2.10 on 2026-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
