# Generated by Django 5.2.10 on 2026-01-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_remove_reward_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedCreditCardInconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inconsistency_type', models.CharField(choices=[('duplicate', 'Duplicate Transaction'), ('cross_card', 'Cross-Card Match'), ('missing_description', 'Missing Description')], max_length=20)),
                ('transaction_ids', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dismissed_at'],
                'unique_together': {('inconsistency_type', 'transaction_ids')},
            },
        ),
    ]
