# Generated by Django 5.2.10 on 2026-01-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_creditcardtransaction_artifact_row_id'),
        ('extractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='data_source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_transactions', to='extractions.datasourceartifact'),
        ),
    ]
