# Generated by Django 5.2.10 on 2026-01-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0003_creditcardtransaction_data_source_artifact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionartifact',
            name='extraction',
        ),
        migrations.RemoveField(
            model_name='creditcardtransaction',
            name='pdf_extraction',
        ),
        migrations.RemoveField(
            model_name='creditcardsourcefile',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='creditcardtransaction',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='extractionartifact',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='extractionartifact',
            name='source_artifact',
        ),
        migrations.RemoveField(
            model_name='creditcardtransaction',
            name='source_artifact',
        ),
        migrations.DeleteModel(
            name='CreditCardPDFExtraction',
        ),
        migrations.DeleteModel(
            name='CreditCardSourceFile',
        ),
        migrations.DeleteModel(
            name='ExtractionArtifact',
        ),
    ]
