# Generated by Django 5.2.10 on 2026-01-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0004_creditcardsourcefile_file_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcardtransaction',
            options={'ordering': ['-date', '-row_number']},
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='row_number',
            field=models.IntegerField(default=0),
        ),
    ]
