# Generated by Django 5.2.10 on 2026-05-23 20:44

import credit_cards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0004_add_transaction_resolution'),
        ('extractions', '0004_alter_transactionlinksnapshot_link_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardEMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_id', models.CharField(default=credit_cards.models.generate_emi_id, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('num_installments', models.IntegerField(blank=True, null=True)),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('foreclosed', 'Foreclosed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emis', to='credit_cards.creditcard')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emis', to='extractions.extractionartifact')),
            ],
            options={
                'db_table': 'credit_cards_creditcardemi',
                'ordering': ['-created_at'],
            },
        ),
    ]
