# Generated by Django 5.2.10 on 2026-01-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0005_alter_creditcardtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardsourcefile',
            name='date_range_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcardsourcefile',
            name='date_range_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
