# Generated by Django 5.2.10 on 2026-01-18 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0007_add_creditcard_extracted_csv_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardPDFExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=48, unique=True)),
                ('transactions_csv_data', models.BinaryField(blank=True, null=True)),
                ('transactions_csv_hash', models.CharField(blank=True, max_length=64)),
                ('transactions_row_count', models.IntegerField(default=0)),
                ('emi_csv_data', models.BinaryField(blank=True, null=True)),
                ('emi_csv_hash', models.CharField(blank=True, max_length=64)),
                ('emi_row_count', models.IntegerField(default=0)),
                ('metadata_json_data', models.BinaryField(blank=True, null=True)),
                ('metadata_json_hash', models.CharField(blank=True, max_length=64)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('card_number_mask', models.CharField(blank=True, max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('total_amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minimum_amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('extractor_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('extracted', 'Extracted'), ('loading', 'Loading'), ('loaded', 'Loaded to DB'), ('error', 'Load Error'), ('superseded', 'Superseded')], default='extracted', max_length=20)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_cards.creditcard')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_extractions', to='credit_cards.creditcardsourcefile')),
            ],
            options={
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='pdf_extraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='credit_cards.creditcardpdfextraction'),
        ),
    ]
