# Generated by Django 5.2.10 on 2026-01-18 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0008_add_creditcardpdfextraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardpdfextraction',
            name='emi_csv_data',
        ),
        migrations.RemoveField(
            model_name='creditcardpdfextraction',
            name='emi_csv_hash',
        ),
        migrations.RemoveField(
            model_name='creditcardpdfextraction',
            name='emi_row_count',
        ),
        migrations.RemoveField(
            model_name='creditcardpdfextraction',
            name='metadata_json_data',
        ),
        migrations.RemoveField(
            model_name='creditcardpdfextraction',
            name='metadata_json_hash',
        ),
        migrations.RemoveField(
            model_name='creditcardpdfextraction',
            name='transactions_csv_data',
        ),
        migrations.RemoveField(
            model_name='creditcardpdfextraction',
            name='transactions_csv_hash',
        ),
        migrations.RemoveField(
            model_name='creditcardpdfextraction',
            name='transactions_row_count',
        ),
        migrations.CreateModel(
            name='ExtractionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('artifact_type', models.CharField(choices=[('transactions', 'Transactions CSV'), ('emi', 'EMI/Loans CSV'), ('metadata', 'Statement Metadata JSON')], max_length=20)),
                ('data', models.BinaryField()),
                ('data_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='credit_cards.creditcardpdfextraction')),
            ],
            options={
                'ordering': ['artifact_type'],
                'unique_together': {('extraction', 'artifact_type')},
            },
        ),
    ]
