# Generated by Django 5.2.10 on 2026-01-18 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0009_add_extractionartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='credit_cards.extractionartifact'),
        ),
    ]
