# Generated by Django 5.2.10 on 2026-01-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0010_add_source_artifact_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardpdfextraction',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
