# Generated by Django 5.2.10 on 2026-01-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0011_add_hidden_to_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardsourcefile',
            name='pdf_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
