# Generated by Django 5.2.10 on 2026-01-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0012_add_pdf_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardpdfextraction',
            name='status',
            field=models.CharField(choices=[('extracted', 'Extracted'), ('transformed', 'Transformed'), ('loading', 'Loading'), ('loaded', 'Loaded to DB'), ('error', 'Load Error'), ('superseded', 'Superseded')], default='extracted', max_length=20),
        ),
        migrations.AlterField(
            model_name='extractionartifact',
            name='artifact_type',
            field=models.CharField(choices=[('transactions', 'Transactions CSV'), ('transactions_ingestable', 'Ingestable Transactions CSV'), ('emi', 'EMI/Loans CSV'), ('metadata', 'Statement Metadata JSON')], max_length=30),
        ),
    ]
