# Generated by Django - Refactoring to pluggable transformer pipeline
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0013_add_transformed_status_and_ingestable_artifact'),
    ]

    operations = [
        # Remove choices constraint and increase max_length
        migrations.AlterField(
            model_name='extractionartifact',
            name='artifact_type',
            field=models.CharField(max_length=50),
        ),
        # Add content_type field
        migrations.AddField(
            model_name='extractionartifact',
            name='content_type',
            field=models.CharField(max_length=20, default='csv'),
        ),
        # Add transformer_name field
        migrations.AddField(
            model_name='extractionartifact',
            name='transformer_name',
            field=models.CharField(max_length=50, blank=True, default=''),
        ),
        # Add is_transformable field
        migrations.AddField(
            model_name='extractionartifact',
            name='is_transformable',
            field=models.BooleanField(default=False),
        ),
        # Add is_transformed field
        migrations.AddField(
            model_name='extractionartifact',
            name='is_transformed',
            field=models.BooleanField(default=False),
        ),
        # Add source_artifact field (self-referential FK)
        migrations.AddField(
            model_name='extractionartifact',
            name='source_artifact',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='derived_artifacts',
                to='credit_cards.extractionartifact',
            ),
        ),
        # Remove unique_together constraint
        migrations.AlterUniqueTogether(
            name='extractionartifact',
            unique_together=set(),
        ),
    ]
