# Generated by Django 5.2.10 on 2026-01-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0017_remove_legacy_csv_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='intl_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
