# Generated by Django 5.2.10 on 2026-01-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accs', '0001_initial_squashed'),
        ('credit_cards', '0002_creditcardtransaction_artifact_row_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_id', models.CharField(blank=True, max_length=32, unique=True)),
                ('extractor_name', models.CharField(max_length=50)),
                ('extractor_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('hidden', models.BooleanField(default=False)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('domain', models.CharField(choices=[('bank_account', 'Bank Account'), ('credit_card', 'Credit Card')], max_length=20)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('extractor', models.CharField(blank=True, max_length=50)),
                ('extraction_status', models.CharField(choices=[('not_extracted', 'Not Extracted'), ('extracted', 'Extracted')], default='not_extracted', max_length=20)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('artifact_type', models.CharField(max_length=50)),
                ('artifact_key', models.CharField(blank=True, max_length=100)),
                ('content_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('txt', 'Plain Text')], default='csv', max_length=10)),
                ('content', models.BinaryField()),
                ('content_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('data_source_target', models.CharField(blank=True, max_length=50)),
                ('transformer', models.CharField(blank=True, max_length=50)),
                ('transformation_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('not_transformed', 'Not Transformed'), ('transformed', 'Transformed')], default='not_applicable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='extractions.extraction')),
            ],
            options={
                'ordering': ['artifact_type'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('data_source_target', models.CharField(choices=[('bank_account_transactions', 'Bank Account Transactions'), ('credit_card_transactions', 'Credit Card Transactions')], max_length=50)),
                ('content', models.BinaryField()),
                ('content_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('transformer', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('unloaded', 'Unloaded'), ('loading', 'Loading'), ('loaded', 'Loaded'), ('error', 'Error')], default='unloaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False)),
                ('transformed_at', models.DateTimeField(auto_now_add=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_source_artifacts', to='bank_accs.bankaccount')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_source_artifacts', to='credit_cards.creditcard')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_source_artifacts', to='extractions.extractionartifact')),
            ],
            options={
                'ordering': ['-transformed_at'],
            },
        ),
        migrations.AddField(
            model_name='extraction',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='extractions.sourcefile'),
        ),
        migrations.CreateModel(
            name='TransactionLinkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('self_transfer', 'Self Transfer'), ('cc_payment', 'Credit Card Payment')], max_length=20)),
                ('source_row_id', models.CharField(max_length=50)),
                ('target_row_id', models.CharField(max_length=50)),
                ('link_metadata', models.JSONField(blank=True, default=dict)),
                ('snapshotted_at', models.DateTimeField(auto_now_add=True)),
                ('data_source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_snapshots', to='extractions.datasourceartifact')),
            ],
            options={
                'ordering': ['-snapshotted_at'],
            },
        ),
    ]
