# Generated by Django 5.2.10 on 2026-01-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0001_initial_squashed'),
        ('credit_cards', '0003_creditcardtransaction_data_source_artifact'),
        ('extractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceartifact',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='datasourceartifact',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='datasourceartifact',
            name='status',
            field=models.CharField(choices=[('unloaded', 'Unloaded'), ('loading', 'Loading'), ('loaded', 'Loaded'), ('error', 'Error')], db_index=True, default='unloaded', max_length=20),
        ),
        migrations.AddIndex(
            model_name='datasourceartifact',
            index=models.Index(fields=['status', 'enabled', 'hidden'], name='ds_art_status_enabled_hidden'),
        ),
    ]
