# Generated by Django 5.2.10 on 2026-02-09 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_add_transaction_resolution'),
        ('credit_cards', '0003_add_transaction_resolution'),
        ('extractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlappingSourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overlapping_groups', to='bank_accounts.bankaccount')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overlapping_groups', to='credit_cards.creditcard')),
                ('data_source_artifacts', models.ManyToManyField(related_name='overlapping_groups', to='extractions.datasourceartifact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('suggesting', 'Generating Suggestions'), ('review', 'In Review'), ('executing', 'Executing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='suggesting', max_length=20)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overlapping_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='extractions.overlappingsourcegroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_transaction_ids', models.JSONField()),
                ('suggestion_score', models.FloatField(default=0.0)),
                ('match_signals', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('modified', 'Modified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('confirmed_primary_id', models.IntegerField(blank=True, null=True)),
                ('confirmed_transaction_ids', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='extractions.resolutionsession')),
            ],
            options={
                'ordering': ['-suggestion_score'],
            },
        ),
        migrations.CreateModel(
            name='ResolvedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('bank', 'Bank Transaction'), ('credit_card', 'Credit Card Transaction')], max_length=20)),
                ('primary_transaction_id', models.IntegerField()),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_transactions', to='bank_accounts.bankaccount')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_transactions', to='credit_cards.creditcard')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['bank_account', 'date'], name='extractions_bank_ac_e124f5_idx'), models.Index(fields=['credit_card', 'date'], name='extractions_credit__8c514f_idx'), models.Index(fields=['uuid'], name='extractions_uuid_2b1b2b_idx')],
            },
        ),
    ]
