# Generated by Django 5.2.10 on 2026-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0003_extend_link_snapshot_for_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlinksnapshot',
            name='link_type',
            field=models.CharField(choices=[('self_transfer', 'Self Transfer'), ('cc_payment', 'Credit Card Payment'), ('refund', 'Refund'), ('category', 'Category'), ('story', 'Story'), ('entity', 'Entity')], max_length=20),
        ),
    ]
