# Generated by Django 5.2.10 on 2026-01-24 00:13

import django.db.models.deletion
import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(default=stories.models.generate_story_id, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📁', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'db_table': 'stories_story',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('bank', 'Bank Transaction'), ('credit_card', 'Credit Card Transaction')], max_length=20)),
                ('transaction_id', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_transactions', to='stories.story')),
            ],
            options={
                'db_table': 'stories_storytransaction',
                'ordering': ['-added_at'],
                'unique_together': {('story', 'transaction_type', 'transaction_id')},
            },
        ),
    ]
