# Generated by Django 5.2.10 on 2026-03-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_icon_charset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryTransaction',
        ),
    ]
