# Generated by Django 5.2.10 on 2026-01-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial_squashed'),
        ('extractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='artifact_row_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='data_source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='extractions.datasourceartifact'),
        ),
    ]
