# Generated by Django 5.2.10 on 2026-01-14 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transaction_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='linked_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='dashboard.transaction'),
        ),
    ]
