# Generated by Django 5.2.10 on 2026-01-22 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transaction_artifact_row_id_and_more'),
        ('extractions', '0002_add_indexes_for_experimental_queries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountlog',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='fileloadlog',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='extracted_csv',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_artifact',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_file',
        ),
        migrations.AddField(
            model_name='fileloadlog',
            name='data_source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_logs', to='extractions.datasourceartifact'),
        ),
        migrations.AlterField(
            model_name='accountlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Account Created'), ('UPDATE', 'Account Updated'), ('DELETE', 'Account Deleted')], max_length=20),
        ),
    ]
