# Generated by Django 5.2.10 on 2026-01-15 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0003_sourcefile_file_hash_sourcefile_last_loaded_at'),
        ('dashboard', '0003_transaction_linked_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bank_accs.sourcefile'),
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOAD', 'Initial Load'), ('CATEGORY_CHANGE', 'Category Change'), ('LINK', 'Transaction Linked'), ('UNLINK', 'Transaction Unlinked')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accs.sourcefile')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
