# Generated by Django 5.2.10 on 2026-01-15 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0003_sourcefile_file_hash_sourcefile_last_loaded_at'),
        ('dashboard', '0004_transaction_source_file_transactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Account Created'), ('UPDATE', 'Account Updated'), ('DELETE', 'Account Deleted'), ('LINK_SOURCE', 'Source File Linked'), ('UNLINK_SOURCE', 'Source File Unlinked')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='bank_accs.bankaccount')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accs.sourcefile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
