# Generated by Django 5.2.10 on 2026-01-15 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0003_sourcefile_file_hash_sourcefile_last_loaded_at'),
        ('dashboard', '0005_add_account_log_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='source_file',
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('CATEGORY_CHANGE', 'Category Change'), ('LINK', 'Transaction Linked'), ('UNLINK', 'Transaction Unlinked')], max_length=20),
        ),
        migrations.CreateModel(
            name='FileLoadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_count', models.IntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('category_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accs.bankaccount')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_logs', to='bank_accs.sourcefile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
