# Generated by Django 5.2.10 on 2026-01-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_add_file_load_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileloadlog',
            name='link_source',
            field=models.CharField(choices=[('pre_existing', 'Pre-existing Link'), ('none', 'No Link')], default='none', max_length=20),
        ),
    ]
