# Generated by Django 5.2.10 on 2026-01-17 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0006_sourcefile_file_data_sourcefile_file_size_and_more'),
        ('dashboard', '0007_add_link_source_to_file_load_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='extracted_csv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bank_accs.extractedcsv'),
        ),
    ]
