# Generated by Django 5.2.10 on 2026-01-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_transaction_extracted_csv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-row_number']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='row_number',
            field=models.IntegerField(default=0),
        ),
    ]
