# Generated by Django 5.2.10 on 2026-01-17 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0007_add_creditcard_extracted_csv_name'),
        ('dashboard', '0009_alter_transaction_options_transaction_row_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardPaymentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('match_reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cc_payment_match', to='dashboard.transaction')),
                ('credit_card_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment_match', to='credit_cards.creditcardtransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
