# Generated by Django 5.2.10 on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_creditcardpaymentmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardpaymentmatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
