# Generated by Django 5.2.1 on 2025-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_creditcardpaymentmatch_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedBankInconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inconsistency_type', models.CharField(choices=[('duplicate', 'Duplicate Transaction'), ('cross_account', 'Cross-Account Match'), ('balance_gap', 'Balance Discontinuity')], max_length=20)),
                ('transaction_ids', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dismissed_at'],
                'unique_together': {('inconsistency_type', 'transaction_ids')},
            },
        ),
    ]
