# Generated by Django 5.2.10 on 2026-01-20 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, unique=True)),
                ('csv_data', models.BinaryField()),
                ('csv_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('extractor_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('extracted', 'Extracted'), ('transformed', 'Transformed'), ('loading', 'Loading'), ('loaded', 'Loaded to DB'), ('error', 'Load Error'), ('superseded', 'Superseded')], default='extracted', max_length=20)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('disabled', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_csvs', to='bank_accs.bankaccount')),
            ],
            options={
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='BankExtractionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('artifact_type', models.CharField(max_length=50)),
                ('content_type', models.CharField(default='csv', max_length=20)),
                ('data', models.BinaryField()),
                ('data_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='bank_accs.bankaccount')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='bank_accs.extractedcsv')),
            ],
            options={
                'ordering': ['artifact_type'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('extractor', models.CharField(choices=[('sbi_pdf', 'SBI PDF Statement'), ('icici_xlsx', 'ICICI Excel Statement'), ('hdfc_txt', 'HDFC Text Statement'), ('generic_xlsx', 'Generic Excel'), ('generic_txt', 'Generic CSV/TXT')], max_length=50)),
                ('file_pattern', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_bank_account', models.ForeignKey(blank=True, help_text='Default bank account for new files matching this pipeline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_pipelines', to='bank_accs.bankaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='extractedcsv',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accs.extractionpipeline'),
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('last_loaded_at', models.DateTimeField(blank=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_files', to='bank_accs.bankaccount')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_files', to='bank_accs.extractionpipeline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='extractedcsv',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_csvs', to='bank_accs.sourcefile'),
        ),
    ]
