# Generated by Django 5.2.10 on 2026-01-14 23:06

import django.db.models.deletion
from django.db import migrations, models


def migrate_source_files(apps, schema_editor):
    """Migrate existing source_file data from BankAccount to SourceFile model."""
    BankAccount = apps.get_model('bank_accs', 'BankAccount')
    SourceFile = apps.get_model('bank_accs', 'SourceFile')

    for account in BankAccount.objects.all():
        if account.source_file:
            SourceFile.objects.get_or_create(
                filename=account.source_file,
                defaults={'bank_account': account}
            )


def reverse_migrate(apps, schema_editor):
    """Reverse migration - copy first source file back to BankAccount."""
    BankAccount = apps.get_model('bank_accs', 'BankAccount')
    SourceFile = apps.get_model('bank_accs', 'SourceFile')

    for account in BankAccount.objects.all():
        source_file = SourceFile.objects.filter(bank_account=account).first()
        if source_file:
            account.source_file = source_file.filename
            account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0001_initial'),
    ]

    operations = [
        # First create the SourceFile model
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_files', to='bank_accs.bankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Migrate existing data
        migrations.RunPython(migrate_source_files, reverse_migrate),
        # Remove the old field
        migrations.RemoveField(
            model_name='bankaccount',
            name='source_file',
        ),
    ]
