# Generated by Django 5.2.10 on 2026-01-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0002_add_source_file_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='last_loaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
