# Generated by Django 5.2.10 on 2026-01-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0003_sourcefile_file_hash_sourcefile_last_loaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
