# Generated by Django 5.2.10 on 2026-01-15 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0004_add_source_file_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('extractor', models.CharField(choices=[('sbi_pdf', 'SBI PDF Statement'), ('icici_xlsx', 'ICICI Excel Statement'), ('hdfc_txt', 'HDFC Text Statement'), ('generic_xlsx', 'Generic Excel'), ('generic_txt', 'Generic CSV/TXT')], max_length=50)),
                ('file_pattern', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_bank_account', models.ForeignKey(blank=True, help_text='Default bank account for new files matching this pipeline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_pipelines', to='bank_accs.bankaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_files', to='bank_accs.extractionpipeline'),
        ),
    ]
