# Generated by Django 5.2.10 on 2026-01-17 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0005_extractionpipeline_sourcefile_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ExtractedCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_data', models.BinaryField()),
                ('csv_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('extractor_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('extracted', 'Extracted'), ('loaded', 'Loaded to DB'), ('error', 'Load Error'), ('superseded', 'Superseded')], default='extracted', max_length=20)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accs.extractionpipeline')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_csvs', to='bank_accs.sourcefile')),
            ],
            options={
                'ordering': ['-extracted_at'],
            },
        ),
    ]
