# Generated by Django 5.2.10 on 2026-01-17 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0007_sourcefile_date_range_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedcsv',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_csvs', to='bank_accs.bankaccount'),
        ),
        migrations.AddField(
            model_name='extractedcsv',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extractedcsv',
            name='status',
            field=models.CharField(choices=[('extracted', 'Extracted'), ('loading', 'Loading'), ('loaded', 'Loaded to DB'), ('error', 'Load Error'), ('superseded', 'Superseded')], default='extracted', max_length=20),
        ),
    ]
