# Generated by Django 5.2.10 on 2026-01-17 15:56

from django.db import migrations


def copy_bank_account_from_source_file(apps, schema_editor):
    """Copy bank_account from source_file to extracted_csv."""
    ExtractedCSV = apps.get_model('bank_accs', 'ExtractedCSV')
    for csv in ExtractedCSV.objects.select_related('source_file').all():
        if csv.source_file and csv.source_file.bank_account_id:
            csv.bank_account_id = csv.source_file.bank_account_id
            csv.save(update_fields=['bank_account_id'])


def reverse_copy(apps, schema_editor):
    """Clear bank_account on extracted_csv (reverse migration)."""
    ExtractedCSV = apps.get_model('bank_accs', 'ExtractedCSV')
    ExtractedCSV.objects.update(bank_account=None)


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0008_extracted_csv_bank_account'),
    ]

    operations = [
        migrations.RunPython(copy_bank_account_from_source_file, reverse_copy),
    ]
