# Generated by Django 5.2.10 on 2026-01-17 16:18

import shortuuid
from django.db import migrations, models


def generate_names(apps, schema_editor):
    """Populate name field for existing ExtractedCSV records."""
    ExtractedCSV = apps.get_model('bank_accs', 'ExtractedCSV')

    existing_names = set(ExtractedCSV.objects.exclude(name='').values_list('name', flat=True))

    for csv in ExtractedCSV.objects.filter(name=''):
        date_str = csv.extracted_at.strftime('%d%m%Y')
        # Generate unique name with collision check
        while True:
            short_id = shortuuid.uuid()[:8]
            candidate = f"extraction_{date_str}_{short_id}"
            if candidate not in existing_names:
                csv.name = candidate
                existing_names.add(candidate)
                csv.save(update_fields=['name'])
                break


def reverse_names(apps, schema_editor):
    """Reverse migration: clear all names."""
    ExtractedCSV = apps.get_model('bank_accs', 'ExtractedCSV')
    ExtractedCSV.objects.all().update(name='')


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0009_copy_bank_account_to_extracted_csv'),
    ]

    operations = [
        # Step 1: Add the name field without unique constraint (to allow empty values during migration)
        migrations.AddField(
            model_name='extractedcsv',
            name='name',
            field=models.CharField(blank=True, max_length=32, default=''),
        ),
        # Step 2: Populate names for existing records
        migrations.RunPython(generate_names, reverse_names),
        # Step 3: Add unique constraint now that all records have names
        migrations.AlterField(
            model_name='extractedcsv',
            name='name',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
