# Generated by Django 5.2.10 on 2026-01-19 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0010_add_extracted_csv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedcsv',
            name='status',
            field=models.CharField(choices=[('extracted', 'Extracted'), ('transformed', 'Transformed'), ('loading', 'Loading'), ('loaded', 'Loaded to DB'), ('error', 'Load Error'), ('superseded', 'Superseded')], default='extracted', max_length=20),
        ),
        migrations.CreateModel(
            name='BankExtractionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('artifact_type', models.CharField(max_length=50)),
                ('content_type', models.CharField(default='csv', max_length=20)),
                ('data', models.BinaryField()),
                ('data_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='bank_accs.bankaccount')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='bank_accs.extractedcsv')),
            ],
            options={
                'ordering': ['artifact_type'],
            },
        ),
    ]
