# Generated by Django 5.2.10 on 2026-01-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accs', '0011_add_bank_extraction_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedcsv',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
