# Generated by Django 5.2.10 on 2026-01-26 16:34

import django.db.models.deletion
import entities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(default=entities.models.generate_entity_id, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='👤', max_length=10)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('business', 'Business')], default='person', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Entities',
                'db_table': 'entities_entity',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('bank', 'Bank Transaction'), ('credit_card', 'Credit Card Transaction')], max_length=20)),
                ('transaction_id', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_transactions', to='entities.entity')),
            ],
            options={
                'db_table': 'entities_entitytransaction',
                'ordering': ['-added_at'],
                'unique_together': {('entity', 'transaction_type', 'transaction_id')},
            },
        ),
    ]
