# Generated by Django 5.2.10 on 2026-03-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_fix_icon_encoding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityTransaction',
        ),
    ]
