# Generated by Django 5.2.10 on 2026-05-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0004_alter_transactionlinksnapshot_link_type'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_original_type', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_refund_type', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_original_transaction_id', models.IntegerField(blank=True, null=True)),
                ('origin_refund_transaction_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_resolved_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_links_as_original', to='extractions.resolvedtransaction')),
                ('refund_resolved_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_links_as_refund', to='extractions.resolvedtransaction')),
            ],
            options={
                'db_table': 'links_refundlink',
                'ordering': ['-created_at'],
            },
        ),
    ]
