# Generated by Django 5.2.10 on 2026-05-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_refundlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundlink',
            name='offset',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
