# Generated by Django 5.2.10 on 2026-05-23 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0005_add_emi_models'),
        ('extractions', '0004_alter_transactionlinksnapshot_link_type'),
        ('links', '0004_backfill_refundlink_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMILink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('purchase', 'Original Purchase'), ('principal', 'Principal Installment'), ('interest', 'Interest Installment'), ('processing_fee', 'Processing Fee'), ('tax', 'Tax'), ('foreclosure', 'Foreclosure Charge'), ('other', 'Other')], default='other', max_length=20)),
                ('installment_number', models.IntegerField(blank=True, null=True)),
                ('origin_transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_transaction_id', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('emi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_links', to='credit_cards.creditcardemi')),
                ('resolved_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emi_links', to='extractions.resolvedtransaction')),
            ],
            options={
                'db_table': 'links_emilink',
                'ordering': ['-added_at'],
                'unique_together': {('resolved_transaction', 'emi')},
            },
        ),
    ]
