# Generated by Django 5.2.10 on 2026-05-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_add_emi_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='emilink',
            name='tax_parent_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_children', to='links.emilink'),
        ),
        migrations.AddField(
            model_name='emilink',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
