# Generated by Django 5.2.10 on 2026-05-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_add_emi_tax_linkage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emilink',
            name='component_type',
            field=models.CharField(choices=[('purchase', 'Original Purchase'), ('loan', 'Loan (EMI Conversion Credit)'), ('principal', 'Principal Installment'), ('interest', 'Interest Installment'), ('processing_fee', 'Processing Fee'), ('tax', 'Tax'), ('foreclosure', 'Foreclosure Charge'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
