# Generated by Django 5.2.10 on 2026-05-28 13:06

import django.db.models.deletion
import links.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0004_alter_transactionlinksnapshot_link_type'),
        ('links', '0007_add_loan_component_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown_id', models.CharField(default=links.models.generate_breakdown_id, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('origin_transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_transaction_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdown', to='extractions.resolvedtransaction')),
            ],
            options={
                'db_table': 'links_breakdown',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakdownPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='links.breakdown')),
                ('rate_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_dependents', to='links.breakdownpart')),
            ],
            options={
                'db_table': 'links_breakdownpart',
                'ordering': ['order', 'id'],
            },
        ),
    ]
