# Generated by Django 5.2.10 on 2026-01-23 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank_accounts_bankaccount',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DismissedBankInconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inconsistency_type', models.CharField(choices=[('duplicate', 'Duplicate Transaction'), ('cross_account', 'Cross-Account Match'), ('balance_gap', 'Balance Discontinuity')], max_length=20)),
                ('transaction_ids', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_accounts_dismissedbankinconsistency',
                'ordering': ['-dismissed_at'],
            },
        ),
        migrations.CreateModel(
            name='FileLoadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_count', models.IntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('category_summary', models.JSONField(blank=True, default=dict)),
                ('link_source', models.CharField(choices=[('pre_existing', 'Pre-existing Link'), ('none', 'No Link')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_accounts_fileloadlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CATEGORY_CHANGE', 'Category Change'), ('LINK', 'Transaction Linked'), ('UNLINK', 'Transaction Unlinked')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_accounts_transactionlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Account Created'), ('UPDATE', 'Account Updated'), ('DELETE', 'Account Deleted')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='bank_accounts.bankaccount')),
            ],
            options={
                'db_table': 'bank_accounts_accountlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('narration', models.TextField()),
                ('value_date', models.DateField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_number', models.CharField(max_length=50)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('artifact_row_id', models.CharField(blank=True, max_length=50)),
                ('row_number', models.IntegerField(default=0)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_accounts.bankaccount')),
            ],
            options={
                'db_table': 'bank_accounts_banktransaction',
                'ordering': ['-date', '-row_number'],
            },
        ),
    ]
