# Generated by Django 5.2.10 on 2026-01-23 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('extractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='data_source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='extractions.datasourceartifact'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='linked_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='bank_accounts.banktransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='dismissedbankinconsistency',
            unique_together={('inconsistency_type', 'transaction_ids')},
        ),
        migrations.AddField(
            model_name='fileloadlog',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accounts.bankaccount'),
        ),
        migrations.AddField(
            model_name='fileloadlog',
            name='data_source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_logs', to='extractions.datasourceartifact'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bank_accounts.banktransaction'),
        ),
    ]
