# Generated by Django 5.2.10 on 2026-01-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial_squashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankextractionartifact',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='bankextractionartifact',
            name='extraction',
        ),
        migrations.RemoveField(
            model_name='extractedcsv',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='extractedcsv',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='extractedcsv',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='extractionpipeline',
            name='default_bank_account',
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='bank_account',
        ),
    ]
