# Generated by Django 5.2.10 on 2026-01-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_remove_bankextractionartifact_bank_account_and_more'),
        ('dashboard', '0003_remove_accountlog_source_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankExtractionArtifact',
        ),
        migrations.DeleteModel(
            name='ExtractedCSV',
        ),
        migrations.DeleteModel(
            name='ExtractionPipeline',
        ),
        migrations.DeleteModel(
            name='SourceFile',
        ),
    ]
