# Generated by Django 5.2.10 on 2026-02-09 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_add_transaction_resolution'),
        ('extractions', '0002_add_transaction_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='resolved_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='extractions.resolvedtransaction'),
        ),
    ]
